language: node_js
node_js:
- 7.5
cache:
- node_modules
- bower_components
before_install:
- npm install -g grunt-cli snazzy
- gem install sass
before_script:
- node_modules/.bin/semistandard --verbose | snazzy
script:
- make build
- make test
- grunt coveralls
notifications:
  slack:
    secure: iz0CoBcz79s70KyZ3Kb4fcQqSRl3mK0mAqoqz5TiXwHRq0tPL/CIy+kNQ15YKykNXg9++7lvhOmxedq6H+0mQSZA4xpTbBPVAgISoPgkW0O7wQv6JFXCh2jhUEcPWx1FFaTNkrrN580XX7IONd+iwjauFb4RTU+388Qa+PkL/Zqq6UEqQluAg1H+njy0+klvi/Iz0eAHBTNPwiqZweZQBRYLkEjsmev/bPY94C2UViQGxCMZ+UEV2LMSLeumqkLMuD9vYrXTGqtg00WW36HcPax2Kju0aLjoycuqqypSZOVRuTdOZ4jvB4YUg+mMn9oC7/NFwvPre+zKHfd6jrjbtX3+4rdCr7AL+npSwAx2wKRkhJthHB+OfQ1paeQ/GRL735+VEpweQJumZ4aGOVbd6NF0kbFR9DpPO+xEUp/9V71FpFvBh5bJd8tcfgDrQLk2FzwsVI935yLdBYcbPb5zWOBwy9lz5uFmaZpeLpNwZRHgKLeC8XrEUsSOq6ef8aZkXBqRXpRD3ZNp9hwK6T7Mpi0gZNc4bRaZBanF1W9E1Hlegm7UNMh3v6ePc+B81eh7KUiydlYurQHuw/eXo+H+91VXkKdjCWowmugXsq8XmBUVNJtglG2A77e7uflsm6bwWKnnds4nwMzEBsAvoiYCm98USv1Fl1vdXRVfoI+zcgo=
before_deploy:
  - make pgp
  - export VERSION=$TRAVIS_TAG
  - make dist
  - export RELEASE_LANDING_JS=$(ls dist/js/landing*.min.js)
  - export RELEASE_MY_WALLET_JS=$(ls dist/js/my-wallet*.min.js)
  - export RELEASE_WALLET_JS=$(ls dist/js/wallet*.min.js)
  - npm shrinkwrap --dev
  - zip -r bower_resolution.zip bower_components/*/.bower.json
deploy:
  provider: releases
  api_key:
    secure: E+nnNRUHhKUHpbxE6itpphwI0JyvKkrl/Npr6dXk6RrtudRLolPYxJWrpit7msVOGsdPP8/dQztJq2YJQvVDrjiu19DjiXr4lsLyK8JshenOObbCEawLBC3ZVHMi2wyekg2JIrXdWDdi3heY0bwjmV0udAvAWbu/533NCKLjOSa3M+jKoVenmh9MCz2D7Z21u8BQ4714CrhM16DrSdP58RCEBsQQmK34BUCNfpUl75t7qLkERhCKtkjNSmX1ruT6nkA5UE6oPdUlFehUuo7lAjhe20E4gjEWOiyu9qeUG7qZM8oW4+dOICqGoJ7GhcGZSkL0zarFexKODcjtcG5o1H1hwwcC4zLytB9aHn8IfkUfkI6lH+GER1HNc2nlDwcpnodL3fwuL+/TZcun0ZBrB2KRgDtsvA9CswmrpSnnGIccT79LhhNimhX5nfgdmzQSwOVtx7QmCQDUGrfktlqouWWxcC5OaHYgiZgh+qcK1Js7+SSCimWbKM0jvKBLDGOWELDSbsdZNugCIoLrGvTw4Q/4HZ90CsJV603Z/FdlrC2iHDxAvOcCK6Oa7Ut7aBDPBCUJKEE1mx/g6+KRm7MycZMlxjpnL3bn7a8TmvxVvQ42D5TFJcJq4hz4QNk6CWGvAnS/Lbcuh1HEBg/ND+X8JFYLL0e0zPJhPol1+BQEr38=
  file:
  - "${RELEASE_LANDING_JS}"
  - "${RELEASE_MY_WALLET_JS}"
  - "${RELEASE_WALLET_JS}"
  - npm-shrinkwrap.json
  - bower_resolution.zip
  on:
    repo: blockchain/My-Wallet-V3-Frontend
    tags: true
